import { ContactBand, CorporatePage, PageHero } from "../components";

export default function EnfoqueVis() {
  return <CorporatePage>
    <PageHero eyebrow="Nuestro enfoque" title="Tu vivienda propia, paso a paso." text="Información clara y acompañamiento cercano para que tomes decisiones con confianza." image="/images/vis-vivienda.jpg" />
    <section className="section"><div className="container split-copy"><div><div className="eyebrow">¿Qué es vivienda VIS?</div><h2>Una alternativa diseñada para ampliar el acceso a vivienda digna.</h2></div><div><p>La Vivienda de Interés Social está orientada a hogares que buscan comprar vivienda dentro de los topes definidos por la normativa colombiana. Puede articular ahorro, crédito y subsidios disponibles.</p><p>Nuestro equipo te ayuda a entender cada condición y a organizar una ruta de compra posible para tu hogar.</p></div></div></section>
    <section className="steps section"><div className="container"><div className="eyebrow light">Ruta hacia tu hogar</div><h2>Cuatro etapas. Un equipo contigo.</h2><div className="steps-grid"><article><b>01</b><h3>Conoce tu capacidad</h3><p>Revisamos ingresos, ahorro y alternativas de financiación.</p></article><article><b>02</b><h3>Elige tu proyecto</h3><p>Encuentra ubicación, tipología y etapa que se ajusten a ti.</p></article><article><b>03</b><h3>Gestiona tus apoyos</h3><p>Te orientamos sobre crédito y subsidios aplicables.</p></article><article><b>04</b><h3>Recibe tu hogar</h3><p>Acompañamiento documental hasta la entrega.</p></article></div></div></section>
    <section className="section"><div className="container faq"><div><div className="eyebrow">Preguntas frecuentes</div><h2>Resolvemos tus dudas.</h2></div><div><details open><summary>¿Quién puede comprar vivienda VIS?<span>+</span></summary><p>Cualquier hogar que cumpla las condiciones financieras del proyecto y los requisitos de la entidad que otorgue el crédito o subsidio.</p></details><details><summary>¿Puedo usar cesantías para la cuota inicial?<span>+</span></summary><p>En muchos casos sí. Nuestro equipo comercial puede orientarte para organizar los soportes requeridos.</p></details><details><summary>¿Qué subsidios puedo solicitar?<span>+</span></summary><p>Depende de tu situación, caja de compensación y programas vigentes. Verificamos contigo las alternativas disponibles.</p></details></div></div></section>
    <ContactBand />
  </CorporatePage>;
}
